- name: set env vars
  shell: |
    export TYPEORM_CONNECTION="{{ lookup('env', 'TYPEORM_CONNECTION')}}"
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES')}}"
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST')}}"
    export TYPEORM_PORT=5432
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME')}}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE')}}"
    export TYPEORM_MIGRATIONS="{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    export TYPEORM_MIGRATIONS_DIR="{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"

- name: update apt package
  become: true
  apt:
    update_cache: true

- name: remove unnecessary deps
  become: true
  apt:
    autoremove: true

- name: upgrade packages
  become: true
  apt:
    upgrade: true

- name: install python.
  become: true
  apt:
    name: ["python3"]
    state: latest

- name: install nodejs
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install pm2
  become: yes
  npm:
    name: "pm2"
    state: present
    global: yes
    production: yes
